# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [--branch, master, --branch, dev]
      - id: requirements-txt-fixer

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_fmt

  - repo: https://github.com/kraymer/brack
    rev: v1.0.0
    hooks:
      - id: brack
        args: [-r, "([[:alpha:]]+-[[:digit:]]+|NO-ISSUE)\/[-_[:alnum:]]+"]

  - repo: local
    hooks:
      - id: tf-module-versions
        files: ".*"
        always_run: true
        name: Check tf module version used
        entry: bash -c '.github/pre-commit/retrieve-module-version.sh > MAINTENANCE.md'
        language: system
